# Generated by Django 4.2.2 on 2023-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_navigation_desc1'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
