# Generated by Django 4.2.2 on 2023-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_navigation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='timestamp',
            field=models.DateTimeField(default='2012-12-12 10:00:00'),
        ),
    ]
